const errorWrapper = (fn) => (req, res, next) => {
  //! bir error var ise next'e g√∂nder!

  try {
    fn(req, res);
  } catch (error) {
    console.log(error);
    next(error);
  }
};

module.exports = errorWrapper;
